### ISSUE TITLE
Feature request: localization

### ISSUE THREAD

**Issue by SlimeDog** [AlonsoAliaga/BetterBees#3]
Please implement localization of all messages; for example:
```
&Plugin up-to-date! You have the latest version!
```

**Comment by AlonsoAliaga** [comment]
That message is only sent in console when checking updates on server start.
Being honest i dont consider an option to change that message is needed, as many other plugins

**Comment by SlimeDog** [comment]
That was just an example. All messages that the plugin sends in-game and to the console should be localizable.

**Comment by AlonsoAliaga** [comment]
All necessary messages are customizable (the three displayed to players)
The messages sent in console for updates and when enabling the plugin will be always in english since its a language used almost everywhere.

However the message sent when a player with permission/OP joins the server and is notified about an available update will be added as configurable in the next update 😃

**Comment by SlimeDog** [comment]
Thank you.

**Comment by AlonsoAliaga** [comment]
All messages are customizable except the ones sent in console.
